#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🧪 Testing code...'
pnpm test ||
( 
  echo "❌🧪 Testing failed, push aborted.";
  false;
)

echo '⛏️  Building code...'
pnpm build ||
( 
  echo "❌⛏️  Building failed, push aborted.";
  false;
)

echo '✅ Push succeeded.'
